/**
 * Parity tests for src/preprocess against Python cellpose.transforms.
 *
 * Fixtures generated by ~/cellpose-js-spike/gen_preprocess_fixtures.py and
 * symlinked into tests/fixtures (the symlink target is gitignored).
 *
 * Gates:
 *   - normalize: max abs diff < 1e-5 (FP32 rounding noise)
 *   - tile:      max abs diff == 0  (pure slicing/copy)
 */
import { describe, it, expect } from 'vitest';
import { readNpy, maxAbsDiff } from './util/npy.js';
import { normalizePerChannel } from '../src/preprocess/normalize.js';
import { makeTiles } from '../src/preprocess/tile.js';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname  = path.dirname(__filename);
const FIX = path.join(__dirname, 'fixtures');

describe('normalize99 parity', () => {
  for (const name of ['norm_small_1ch', 'norm_small_3ch', 'norm_med_3ch']) {
    it(name, () => {
      const inp = readNpy(path.join(FIX, `${name}_input_chw.npy`));
      const exp = readNpy(path.join(FIX, `${name}_normalized_chw.npy`));
      const [c, h, w] = inp.shape as [number, number, number];
      const got = normalizePerChannel(inp.data, c, h * w);
      const err = maxAbsDiff(exp.data, got);
      expect(err).toBeLessThan(1e-5);
    });
  }
});

describe('make_tiles parity', () => {
  for (const name of ['tile_smaller', 'tile_exact_256', 'tile_grid', 'tile_tall']) {
    it(name, () => {
      const inp = readNpy(path.join(FIX, `${name}_input_chw.npy`));
      const expTiles = readNpy(path.join(FIX, `${name}_tiles_chw.npy`));
      const meta = JSON.parse(fs.readFileSync(path.join(FIX, `${name}_tiles_meta.json`), 'utf8'));
      const [c, h, w] = inp.shape as [number, number, number];

      const got = makeTiles(inp.data, w, h, c, { bsize: meta.bsize, overlap: 0.1 });

      // Tile count matches Python make_tiles
      expect(got.length).toBe(meta.tiles.length);

      // Tile origins match exactly
      for (let i = 0; i < got.length; i++) {
        const g = got[i]!;
        expect({ tx: g.tx, ty: g.ty }).toEqual(meta.tiles[i]);
      }

      // Python make_tiles returns variable-size tiles (min(bsize, Ly/Lx))
      // when the image is smaller than bsize on an axis. Our JS always emits
      // zero-padded (bsize, bsize) tiles for downstream model convenience.
      // Compare just the valid (copyH x copyW) region of each tile.
      const B = meta.bsize as number;
      const expDims = expTiles.shape; // (ntiles, C, vH, vW)
      const [, , vH, vW] = expDims as [number, number, number, number];
      const tileLenExp = c * vH * vW;
      for (let ti = 0; ti < got.length; ti++) {
        const t = got[ti]!;
        const expSlice = expTiles.data.subarray(ti * tileLenExp, (ti + 1) * tileLenExp);
        // Pull the (C, vH, vW) valid region out of t.tile (C, B, B).
        const gotSlice = new Float32Array(tileLenExp);
        for (let cc = 0; cc < c; cc++) {
          for (let yy = 0; yy < vH; yy++) {
            const srcOff = cc * B * B + yy * B;
            const dstOff = cc * vH * vW + yy * vW;
            gotSlice.set(t.tile.subarray(srcOff, srcOff + vW), dstOff);
          }
        }
        const err = maxAbsDiff(expSlice, gotSlice);
        expect(err).toBe(0);
      }
    });
  }
});
